networks:
  default:
    external: true
    name: ${NETWORK:-dev-network}

services:
  fluentd:
    build: ./elastic
    volumes:
      - ./conf:/fluentd/etc:ro
    ports:
      - 24224:24224
  caddy:
    image: caddy:latest
    ports:
      - 8080-8089:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
    links:
      - fluentd
    logging:
      driver: "fluentd"
      options:
        fluentd-address: localhost:24224
        tag: caddy.weblog
