networks:
  default:
    external: true
    name: ${NETWORK:-dev-network}

volumes:
  log-data:
    driver: local

services:
  # tool:
  #   image: busybox
  #   command:
  #     - sh
  #     - -c
  #     - mkdir -p /data/log/; chmod -R 777 /data/; 
  #   volumes:
  #     - log-data:/data

  fluentd:
    build: ./elastic
    volumes:
      - ./conf:/fluentd/etc:ro
      - log-data:/data
    ports:
      - 24224:24224
  caddy:
    image: caddy:latest
    ports:
      - 8080-8089:80
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - log-data:/data/log
    # links:
    #   - fluentd
    # logging:
    #   driver: "fluentd"
    #   options:
    #     fluentd-address: localhost:24224
    #     tag: caddy.weblog
