version: '2.1'
services:  
  kafka:
    build: ../zk-kafka-stack/
    ports:
      - :61208
      - :9092
      - :2181
    networks:
     - dev
    volumes:
     - kbroker:/data
     - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
     - ":9000"
    depends_on:
     - kafka
    networks:
     - dev
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: -Xms32M -Xmx64M -Xss180K -XX:-TieredCompilation -XX:+UseStringDeduplication -noverify
      SERVER_SERVLET_CONTEXTPATH: /

  kowl:
    image: quay.io/cloudhut/kowl
    environment:
     - KAFKA_BROKERS=kafka:9093
    ports:
     - :8080
    networks:
     - dev
    depends_on:
     - kafka
    restart: unless-stopped

volumes:
  kbroker:
    driver: local

networks:
  dev:    
    name: ${KAFKA_NETWORK:-dev-network}
