version: '2.1'
services:  
  kafka:
    hostname: kafka
    image: s7i/zk-kafka-stack:0.1
    environment:
      - |
        KAFKA_SERVER_PROPERTIES=
        advertised.listeners=DC://:9093, kafka_lo://localhost:9092
        listeners=DC://0.0.0.0:9093, kafka_lo://0.0.0.0:9092        
        listener.security.protocol.map=DC:PLAINTEXT,kafka_lo:PLAINTEXT
        inter.broker.listener.name=kafka_lo

    ports:
      - 61208:61208
      - 9092:9092
      - 2181:2181
    networks:
     - dev
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock

  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
     - "9000:9000"
    depends_on:
     - kafka
    networks:
     - dev
    environment:
      KAFKA_BROKERCONNECT: kafka:9093
      JVM_OPTS: -Xms32M -Xmx64M
      SERVER_SERVLET_CONTEXTPATH: /

networks:
  dev:    
    name: dev-network
